title: Hi I'm CS!
descrition: Testing website stuff here :>
logo: /assets/img/logo.png
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

permalink: /:slug

plugins:
  - jekyll-redirect-from
