title: Ateneo CODE
descrition: Ateneo CODE web url shortner - beta
logo: /assets/img/logo.png
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

permalink: /:slug

plugins:
  - jekyll-redirect-from
