title: Ateneo CODE
description: Ateneo CODE web url shortner
logo: /assets/img/logo.png
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal

permalink: /:slug

plugins:
  - jekyll-redirect-from
