title: Hi I'm CS!
descrition: Testing website stuff here :>
logo: /assets/img/logo.png
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

permalink: /:slug

plugins:
  - jekyll-redirect-from

- name: urlzap
  uses: brunoluiz/urlzap-github-action@v1
